"""empty message

Revision ID: b3b01cefc7e6
Revises: bfaac96484a4
Create Date: 2025-05-14 00:04:29.014617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b01cefc7e6'
down_revision = 'bfaac96484a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_recipes',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='saved_recipes_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='saved_recipes_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
